version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
<<<<<<< HEAD
        image: php:8-alpine
=======
        image: php:7-alpine
>>>>>>> a475f9d (Slim App)
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
